models/inventory.py
class Inventory:
    def __init__(self, item_name, manufacturer, description,stock_quantity,buying_cost,selling_cost,id=None):
        self.item_name = item_name
        self.manufacturer = manufacturer
        self.description = description
        self.stock_quantity = stock_quantity
        self.buying_cost = buying_cost
        self.selling_cost = selling_cost
        self.id = id

 
    

models/manufacturers.py
class Manufacturers:
    def __init__(self, company_name, description, id = None):
        self.company_name = company_name
        self.description = description
        self.id = id 

    def full_company_name(self):
        return f"{self.company_name} {self.description}"

app.py
from flask import Flask, render_template
from controllers.inventory_controller import inventory_blueprint

app = Flask(__name__)

app.register_blueprint(inventory_blueprint)

@app.route('/')
def home():
    return render_template('index.html')


if __name__ =="__main__":
    app.run(debug=True)

controllers/inventory_controller.py
from models.manufacturers import Manufacturers
from flask import Flask, render_template, request,redirect
from repositories import inventory_repository, manufacturer_repository
import repositories.inventory_repository as inventory_repository
import repositories.manufacturer_repository as manufacturer_repository
from models.inventory import Inventory


from flask import Blueprint

inventory_blueprint = Blueprint("inventory",__name__)


@inventory_blueprint.route("/inventory")
def inventory():
    inventory = inventory_repository.select_all()
    return render_template("inventory/index.html",all_inventory = inventory)

@inventory_blueprint.route("/inventory/new")
def new_item():
    manufacturer= manufacturer_repository.select_all()
    return render_template("inventory/new.html", all_manufacturers = manufacturer)

@inventory_blueprint.route("/inventory", methods=["POST"])
def create_inventory():
        item_name = request.form['item_name']
        manufacturer = manufacturer_repository.select(request.form['manufacturers_id'])
        description = request.form['description']
        stock_quantity = request.form['stock_quantity']
        buying_cost = request.form['buying_cost']
        selling_cost = request.form['selling_cost']
        inventory = Inventory(item_name,manufacturer,description,stock_quantity,buying_cost,selling_cost)
        inventory_repository.save(inventory)
        return redirect('/inventory')


# Show
@inventory_blueprint.route("/inventory/<id>", methods=['GET'])
def show_inventory(id):
    inventory = inventory_repository.select(id)
    return render_template('inventory/show.html',inventory = inventory)


# EDIT
@inventory_blueprint.route("/inventory/<id>/edit", methods = ['GET'])
def edit_inventory(id):
    inventory = inventory_repository.select(id)
    manufacturer = manufacturer_repository.select_all()
    return render_template('inventory/edit.html', inventory=inventory, all_manufacturers = manufacturer)

# UPDATE
@inventory_blueprint.route("/inventory/<id>", methods=['POST'])
def update_inventory(id):
        item_name = request.form['item_name']
        manufacturer = manufacturer_repository.select(request.form['manufacturer_id'])
        description = request.form['description']
        stock_quantity = request.form['stock_quantity']
        buying_cost = request.form['buying_cost']
        selling_cost = request.form['selling_cost']
        inventory = Inventory(item_name,manufacturer,description,stock_quantity,buying_cost,selling_cost)
        inventory_repository.update(inventory)
        return redirect('/inventory')


# DELETE
@inventory_blueprint.route("/inventory/<id>/delete", methods=['POST'])
def delete_inventory(id):
    inventory_repository.delete(id)
    return redirect('/inventory')

controllers/manufacturers_controller.py
from models.manufacturers import Manufacturers
from flask import Flask, render_template, request,redirect
from repositories import inventory_repository, manufacturer_repository
import repositories.inventory_repository as inventory_repository
import repositories.manufacturer_repository as manufacturer_repository
from models.inventory import Inventory

from flask import Blueprint
manufacturer_blueprint = Blueprint("inventory",__name__)

@manufacturer_blueprint.route("/inventory/manufacturer")
def inventory():
    inventory = inventory_repository.select_all()
    return render_template("inventory/index.html",all_inventory = inventory)

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial=sacale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"crossorigin>
        <link href="https://fonts...." rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">
        <link rel="stylesheet" href="style.css"/>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous"> 
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='form.css') }}">
        <title>Potion Brew</title>
    </head>
        <header>
            <video muted autoplay loop id="video-background">
                <source src="/static/videos/pexels-rostislav-uzunov-5453622.mp4" type="video/mp4"/>
            </video>

            <div class="header-content">
                <div class="top">
                    <a class="brand" href="#">PBrew</a>
                    <div class="icons">
                       <a href="{{url_for('home')}}">
                            <span class="material-icons-outlined">
                                home
                             </span>
                             
                        </a>
                        <a href="{{url_for('inventory.inventory')}}">
                            <span class="material-icons-outlined">
                                inventory_2
                            </span>
                        </a>
                        <a href="{{url_for('inventory.new_item')}}">
                            <span class="material-icons-outlined">
                                post_add
                            </span>
                        </a>
                    </div>
                </div>
                <div class="middle">
                    <h4>instagram
                        <span class="slash">/</span> @PotionBrew
                    </h4>
                    <div>
                        <h1>POTION BREW</h1>
                        <a href="#" class="play-btn">
                            <span class="material-icons">
                            play_arrow
                            </span>
                        </a>
                    </div>
                    <h4>Potions
                        <span class="slash">/</span> PotionBrew
                    </h4>
                    </div>
                    <div class="bottom">
                        <div>
                            <h2>
                                Your
                                <span class="underline">Potion Brew</span>
                                Masters
                            </h2>
                            <small>Since 1800</small>
                        </div>
                        <div class="arrow">
                            <span class="material-icons-outlined">
                                expand_more
                            </span>
                        </div>
                        
                    </div>
                </div>
            </div>
            
        </header>
        <div class="container">
            {% block content%}
            {%endblock%}
        </div>
    </body>
</html>

templates/index.html
{% extends "base.html"%}
{% block content%}
<section id="home-image">
    
</section>
{%endblock%}

templates/inventory/edit.html
{%extend "base.html"%}
{%block content%}

<form action="/inventory{{inventory.id}}" method="post">
<div>
    <label for="item_name">Name:</label>
    <input type="text" id="item_name" name="name" value="{{inventory.item_name}}" required>
</div>
<div>
    <label for="description">Description:</label>
    <input type="text" id="description" name="description" value="{{inventory.description}}" required autofocus>
</div>
<div>
<label for="stock_quantity">Quantity:</label>
<input type="number" id="Quantity" name="stock_quantity" value="{{inventory.stock_quantity}}" required autofocus>
</div>

<div>
<label for="buying_cost">Buying Cost:</label>
<input type="number" id="buying_cost" name="buying_cost" value="{{inventory.buying_cost}}" required autofocus>
</div>

<div>
    <label for="selling_cost">Selling Cost:</label>
    <input type="number" id="selling_cost" name="selling_cost" value="{{inventory.selling_cost}}" required autofocus>
    </div>

<div>
<label for="manufacturer">Manufacturer:</label>
<select id="manufacturer" name="manufacturer_id">
  {% for manufacturer in all_manufacturers %}
    <option value="{{ manufacturer.id }}"
      {% if book.author.id == manufacturer.id %} selected="selected"{% endif %}>
      {{ manufacturer.company_name() }}
    </option>
  {% endfor %}
</select>
</div>

<button type="submit">Update Book</button>

</form>

{% endblock %}
</form>

templates/inventory/index.html
{%extends "base.html"%}
{%block content%}

<div class="inventory-container">

{%for inventory in all_inventory %}
     <div class="inventory">
        <div class="content">
            <a href="/inventory/{{inventory.id}}">{{inventory.item_name}}<span>Welcome!</span></a>
            <div class="item_name">
                Inventory id: {{inventory.id}}
                {{inventory.description}}
                <span class="manufacturer">{{inventory.manufacturer.description}}</span>
                <p><i>{{inventory.manufacturer.company_name}}</i></p>
                </div>
                <div class="buttons">
                    <form class="delete-form" action="/inventory/{{inventory.id}}/delete" method="POST">
                        <button class="trash-button" type="submit"><i class="fa fa-trash-o fa-3x" style="color:red" aria-hidden="true"></i></button>
                    </form>
                </div>
            </div>
        </div>

        
    </div> 
    <p>{{inventory.item_name}}</p>
    {%endfor%} 
</div>
{% endblock %}

templates/inventory/new.html
{%extends "base.html"%}

{%block content%}
<div class="new-inventory"></div>


<form action="/inventory" method="post">
    <div>
        <label for="item_name">Name:</label>
        <input type="text" id="item_name" name="item_name">
        
    </div>
    <div>
        <label for="description">Description:</label>
        <input type="text" id="description" name="description">
    </div>
    <div>
        <label for="manufacturers_id">Manufacturer:</label>
        <select name="manufacturers_id" id="manufacturers_id">

            {% for manufacturer in all_manufacturers %}
            <option value="{{manufacturer.id}}"> {{manufacturer.company_name}}</option>
            {%endfor%}
        </select>
    </div>

    <div>
        <label for="stock_quantity">Quantity:</label>
        <input type="number" id="stock_quantity" name="stock_quantity">
    </div>
    <div>
        <label for="buying_cost">Buying Cost:</label>
        <input type="number" id="buying_cost" name="buying_cost">
    </div>
    <div>
        <label for="selling_cost">Selling Price:</label>
        <input type="number" id="selling_cost" name="selling_cost">
    </div>
    <div class="rgb-border">
        <a class="btn" href="a">Add Product!</a>
        <!-- <button type="submit">Add product!</button> -->
    </div>      
</form>


{%endblock%}

templates/inventory/show.html
{% extends "base.html"%}
{%block content%}

<div>
    <p>{{inventory.item_name}}</p>
    <hr>
    <p>{{inventory.manufacturer.company_name}}</p>
    <p>{{inventory.description}}</p>
    <p>{{inventory.stock_quantity}}</p>
    <p>{{inventory.buying_cost}}</p>
    <p>{{inventory.selling_cost}}</p>
    <p><a href="/inventory/{{inventory.id}}/edit">Edit</a></p>

</div>

{%endblock%}